version: "3.9"

services:

  prod:
    build:
      context: .
      target: prod
    env_file:
      - .env
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MODE
    command:
      - sh
      - -c
      - |
        python3 -m src.shortener_app.db.drop_create_tables &&
        python3 -m src.main
        python3 -m src.asyncclient
    depends_on:
      prod_db:
        condition: service_healthy
    ports:
      - "8080:8080"

  dev:
    build:
      context: .
      target: dev
    env_file:
      - .env
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MODE
    command:
      - sh
      - -c
      - |
        python3 -m src.shortener_app.db.drop_create_tables &&
        python3 -m src.main
        python3 -m src.asyncclient
    depends_on:
      dev_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  test:
    build:
      context: .
      target: test
    env_file:
      - .env
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MODE
    command:
      - sh
      - -c
      - pytest --cov=src -v
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - .:/app

  prod_db:
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=prod_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  test_db:
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dev_db:
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    environment:
      - POSTGRES_DB=dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5435:5432"

  pg_admin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    depends_on:
      - prod_db
      - test_db
      - dev_db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
    env_file:
      - .env
