from typing import Protocol, Any


class SessionProto(Protocol):
    """
    Protocol for ORM session object.

    This protocol describes interface for asynchronous database
    session object. It's used in Repository class to define interface
    of database operations.
    """
    async def execute(self, *args: Any, **kwargs: Any) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...
    async def flush(self) -> None: ...
    async def get(self, model_cl: Any, instance_id: int) -> Any: ...
    def add(self, instance: Any) -> None: ...
    async def delete(self, instance: Any) -> None: ...
